config/routes.rb
Rails.application.routes.draw do
  get '/articles', to: 'articles#index', as: 'articles'
  get 'articles/new', to: 'articles#new', as: 'new'
  post '/articles', to: 'articles#create', as: 'create'
  get 'articles/:id/edit', to: 'articles#edit', as: 'edit'
  patch 'article/:id', to: 'articles#update', as: 'update'
  get '/article/:id', to: 'articles#show', as: 'article'
  delete '/article/:id', to: 'articles#destroy', as: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/articles/create.html.erb
create.html.erb

app/views/articles/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Edit: <%= @article.title %></h1>
    <%= render 'form', article: @article %>
      <div class="go_back_link">
        <%= link_to articles_path do %>
        <button class="btn btn-success"><i class="fas fa-undo"></i>Go Back to Articles List</button>
        <% end %>
      </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="wrapper">
  <div class="container"><h1>Articles</h1>
    <div class="articles">
      <div class="row">
        <% @articles.each do |article| %>
          <%= link_to article_path(article.id) do %>
          <h3> <%=article.title  %> </h3>
          <% end %>
        <%= link_to delete_path(article.id), method: :delete do %>
        <i class="far fa-trash-alt"></i>
        <% end %>
        <% end %>
      </div>
    </div>
    <hr>
    <%= link_to new_path do %>
    <button class="btn btn-success">Add a new Article</button>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Add a new Article Here:</h1>
    <%= render 'form', article: @article %>
      <div class="go_back_link">
        <%= link_to articles_path do %>
        <button class="btn btn-success"><i class="fas fa-undo"></i>Go Back to Articles List</button>
        <% end %>
      </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="article">
      <h1> <%= @article.title %> </h1>
      <hr>
      <p> <%= @article.content %> </p>
        <div class="go_back_link">
          <%= link_to articles_path do %>
          <button class="btn btn-success"><i class="fas fa-undo"></i>Go Back to Articles List</button>
          <% end %>
        <div class="edit-button">
          <%= link_to edit_path do %>
          <button class="btn btn-success">Edit this Article</button>
          <% end %>
        </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>